version: '2'
services:
    crmcemaco-app:
        image: crmcemaco
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://crmcemaco-mysql:3306/crmcemaco?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    crmcemaco-mysql:
        extends:
            file: mysql.yml
            service: crmcemaco-mysql
